In [1]:
import numpy as np

In [6]:
"""
Write a program called banded_matrix that uses nested for loops to produce an n by n (square) matrix A 
with 0's down the main diagonal, 1's in the entries just above and below the main diagonal, 2's above and below that, 
etc.  The matrix should look like this when n = 5:
"""

n = 5
M = np.zeros((5,5))
M[0][2] = 1
print(M)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
